services:
  signet-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: signet-api
    restart: unless-stopped
    networks:
      - signet-network
    expose:
      - "8000"
    #environment:
    #  - NODE_ENV=production
    # Add any volumes your service needs
    # volumes:
    #   - ./data:/app/data

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - signet-network
    depends_on:
      - signet-api
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  # Certbot for Let's Encrypt SSL certificates
  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  signet-network:
    driver: bridge

volumes:
  certbot-conf:
  certbot-www: